# Base image with Chromium and Node preinstalled
FROM ghcr.io/puppeteer/puppeteer:24.8.2

# Switch to root to install additional dependencies
USER root

# Install XVFB for headless display
RUN apt-get update && \
    apt-get install -y xvfb

# Switch back to node user
USER node

# Set environment variables
ENV DISPLAY=:99
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

# Set working directory
WORKDIR /usr/src/app

# Copy only package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of your server code
COPY . .

# Start the server with virtual display
CMD xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" npx nodemon index.js
